<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="View\фон2.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.2.2-ci921" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.2-ci921" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\фон2.jpg" />
  </ItemGroup>

</Project>
